#!/bin/csh

echo "<html><body>" 
echo "<table border=2>" 

echo "<TR>"
echo "<TD> Hostname"
echo "<TD> # Processors"
echo "<TD> Processors"
echo "<TD> Speed"
echo "<TD> Bogomips"
echo "<TD> Memory"
echo "<TD> Disk"


foreach host ( $* )
  ssh $host resources 
end

echo "</table>" 
echo "</body></html>"


