default: 
	rm resources.html resources.tex
	getresources antares hyades praesepe virgo astronomy astrodisk >resources.html
	getresources_tex antares hyades praesepe virgo astronomy astrodisk >resources.tex
	pdflatex resources

