#!/bin/csh

# load up resources into variables
source ~/bin/resources

# output into LaTeX table row
# note that disks have to be handled specially for more than one, so that
# multiple disks are put on separate table lines
echo  "$host & $nproc & $proc & $speed & $mips & $mem & $disk1\\\\"
echo "$disks"
