#!/bin/csh

set host = `hostname -s`
set nproc=`grep processor /proc/cpuinfo | wc -l`
set proc=`cat /proc/cpuinfo | grep "model name" | awk -F: '{print $2}' | head -1`
set speed=`cat /proc/cpuinfo | grep MHz | awk -F: '{print $2}' | head -1`
set mips=`cat /proc/cpuinfo | grep "bogomips" | awk -F: 'NR==1 {print $2}'`
set mem=`grep MemTotal /proc/meminfo | awk -F: '{print $2}'`
set disk=`df -h | grep dev | grep -v shm | grep -v boot | awk '{printf("<tr><td>%s<td>%s\n",$6, $2)}'`

echo "<TR>"
echo "<TD>" $host
echo "<TD><center>" $nproc "</center>"
echo "<TD>" $proc
echo "<TD>" $speed
echo "<TD>" $mips
echo "<TD>" $mem
echo "<TD><table border=1>" $disk
echo "</table>"
