#!/bin/csh

# load up the resource variables
source ~/bin/resources

# output a row of an HTML table
echo "<TR>"
echo "<TD>" $host
echo "<TD><center>" $nproc "</center>"
echo "<TD>" $proc
echo "<TD>" $speed
echo "<TD>" $mips
echo "<TD>" $mem
echo "<TD><table border=1>" $disk
echo "</table>"
